In [2]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

# Configurar pandas para mostrar más columnas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [5]:
# Rutas (ajusta la carpeta raw donde tengas los CSVs)
raw_path = 'data/raw/'
processed_path = 'data/processed/'
os.makedirs(processed_path, exist_ok=True)

# Lista de archivos a cargar
files = {
    'customers': 'olist_customers_dataset.csv',
    'geolocation': 'olist_geolocation_dataset.csv',
    'order_items': 'olist_order_items_dataset.csv',
    'order_payments': 'olist_order_payments_dataset.csv',
    'order_reviews': 'olist_order_reviews_dataset.csv',
    'orders': 'olist_orders_dataset.csv',
    'products': 'olist_products_dataset.csv',
    'sellers': 'olist_sellers_dataset.csv',
    'category_translation': 'product_category_name_translation.csv'  # opcional
}

# Cargar cada archivo en un diccionario de DataFrames
dfs = {}
for name, file in files.items():
    path = os.path.join(raw_path, file)
    if os.path.exists(path):
        dfs[name] = pd.read_csv(path)
        print(f"Cargado: {name} -> {dfs[name].shape}")
    else:
        print(f"No encontrado: {path}")

Cargado: customers -> (99441, 5)
Cargado: geolocation -> (1000163, 5)
Cargado: order_items -> (112650, 7)
Cargado: order_payments -> (103886, 5)
Cargado: order_reviews -> (99224, 7)
Cargado: orders -> (99441, 8)
Cargado: products -> (32951, 9)
Cargado: sellers -> (3095, 4)
Cargado: category_translation -> (71, 2)

In [8]:
# Ver información general de cada tabla
for name, df in dfs.items():
    print(f"\n=== {name} ===")
    print(f"Shape: {df.shape}")
    print(f"Columnas: {list(df.columns)}")
    print(f"Nulos por columna:\n{df.isnull().sum()}")
    print(f"Duplicados fila completas: {df.duplicated().sum()}")
    # Mostrar primeras filas
    display(df.head(2))

=== customers ===
Shape: (99441, 5)
Columnas: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
Nulos por columna:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Duplicados fila completas: 0

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

=== geolocation ===
Shape: (1000163, 5)
Columnas: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']
Nulos por columna:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
Duplicados fila completas: 261831

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

=== order_items ===
Shape: (112650, 7)
Columnas: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
Nulos por columna:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
Duplicados fila completas: 0

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

=== order_payments ===
Shape: (103886, 5)
Columnas: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
Nulos por columna:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
Duplicados fila completas: 0

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

=== order_reviews ===
Shape: (99224, 7)
Columnas: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
Nulos por columna:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
Duplicados fila completas: 0

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13

=== orders ===
Shape: (99441, 8)
Columnas: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
Nulos por columna:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
Duplicados fila completas: 0

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

=== products ===
Shape: (32951, 9)
Columnas: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
Nulos por columna:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Duplicados fila completas: 0

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

=== sellers ===
Shape: (3095, 4)
Columnas: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
Nulos por columna:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
Duplicados fila completas: 0

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

=== category_translation ===
Shape: (71, 2)
Columnas: ['product_category_name', 'product_category_name_english']
Nulos por columna:
product_category_name            0
product_category_name_english    0
dtype: int64
Duplicados fila completas: 0

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

In [10]:
# Trabajar sobre copia para no modificar original
orders = dfs['orders'].copy()

# Columnas de fecha
date_cols = ['order_purchase_timestamp', 'order_approved_at', 
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date']

for col in date_cols:
    if col in orders.columns:
        orders[col] = pd.to_datetime(orders[col], errors='coerce')  # errores->NaT

# Revisar estado de pedidos
print(orders['order_status'].value_counts())

# Guardar limpias (sobrescribimos en dfs)
dfs['orders'] = orders

display(orders.head(2))

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13

In [11]:
items = dfs['order_items'].copy()

# Convertir precio y flete a float
items['price'] = pd.to_numeric(items['price'], errors='coerce')
items['freight_value'] = pd.to_numeric(items['freight_value'], errors='coerce')

# Ver si hay precios negativos o cero
print(f"Precios <= 0: {(items['price'] <= 0).sum()}")
# Opcional: eliminar filas con precio <= 0 (son datos erróneos)
items = items[items['price'] > 0]

dfs['order_items'] = items

display(items.head(2))

Precios <= 0: 0

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [12]:
payments = dfs['order_payments'].copy()
payments['payment_value'] = pd.to_numeric(payments['payment_value'], errors='coerce')
payments['payment_installments'] = pd.to_numeric(payments['payment_installments'], errors='coerce')

# Agrupar pagos por order_id (un pedido puede tener múltiples formas de pago)
# Esto lo haremos más adelante. Por ahora solo limpiar nulos.
# Eliminar filas sin payment_value
payments = payments.dropna(subset=['payment_value'])

dfs['order_payments'] = payments
display(payments.head(2))

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39

In [13]:
reviews = dfs['order_reviews'].copy()
reviews['review_score'] = pd.to_numeric(reviews['review_score'], errors='coerce')

# Convertir fecha de respuesta si existe
if 'review_answer_timestamp' in reviews.columns:
    reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'], errors='coerce')

dfs['order_reviews'] = reviews
display(reviews.head(2))

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13

In [15]:
customers = dfs['customers'].copy()
sellers = dfs['sellers'].copy()

# Ver nulos (no debería haber)
print("Clientes nulos:\n", customers.isnull().sum())
print("Vendedores nulos:\n", sellers.isnull().sum())

# Ambos tienen zip_code_prefix como string, lo dejamos así.

dfs['customers'] = customers
dfs['sellers'] = sellers
display(customers.head(2))
display(sellers.head(2))

Clientes nulos:
 customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
Vendedores nulos:
 seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP

In [17]:
products = dfs['products'].copy()

# Las columnas numéricas (altura, peso, etc.) pueden tener nulos. Los dejamos por ahora.
numeric_prod = ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
for col in numeric_prod:
    products[col] = pd.to_numeric(products[col], errors='coerce')

# Si hay categoría nula, la etiquetamos como 'desconocida'
products['product_category_name'] = products['product_category_name'].fillna('unknown')

dfs['products'] = products
display(products.head(2))

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0

In [18]:
geo = dfs['geolocation'].copy()

# Quedarnos con la primera ocurrencia de cada zip_code_prefix (la más común)
geo = geo.drop_duplicates(subset=['geolocation_zip_code_prefix'], keep='first')

dfs['geolocation'] = geo
display(geo.head(2))

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP

In [19]:
if 'category_translation' in dfs:
    cat_trans = dfs['category_translation'].copy()
    # Limpiar nombres
    cat_trans['product_category_name_english'] = cat_trans['product_category_name_english'].str.lower().str.strip()
    dfs['category_translation'] = cat_trans
    display(cat_trans.head(2))

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

## Validación de valores nulos críticos

In [20]:
# Verificar que las claves foráneas no tengan nulos donde no deberían
critical_checks = [
    (orders, 'order_id', 'No debe haber nulos en order_id'),
    (orders, 'customer_id', 'No debe haber nulos en customer_id'),
    (items, 'order_id', 'No debe haber nulos en order_id'),
    (items, 'product_id', 'No debe haber nulos en product_id'),
    (items, 'seller_id', 'No debe haber nulos en seller_id')
]

for df, col, msg in critical_checks:
    nulos = df[col].isnull().sum()
    if nulos > 0:
        print(f"⚠️ {msg}: {nulos} nulos")
    else:
        print(f"✅ {msg}")

✅ No debe haber nulos en order_id
✅ No debe haber nulos en customer_id
✅ No debe haber nulos en order_id
✅ No debe haber nulos en product_id
✅ No debe haber nulos en seller_id

In [21]:
# Guardar cada tabla limpia en processed
for name, df in dfs.items():
    output_file = os.path.join(processed_path, f'{name}_clean.csv')
    df.to_csv(output_file, index=False)
    print(f"Guardado: {output_file} ({df.shape})")

Guardado: data/processed/customers_clean.csv ((99441, 5))
Guardado: data/processed/geolocation_clean.csv ((19015, 5))
Guardado: data/processed/order_items_clean.csv ((112650, 7))
Guardado: data/processed/order_payments_clean.csv ((103886, 5))
Guardado: data/processed/order_reviews_clean.csv ((99224, 7))
Guardado: data/processed/orders_clean.csv ((99441, 8))
Guardado: data/processed/products_clean.csv ((32951, 9))
Guardado: data/processed/sellers_clean.csv ((3095, 4))
Guardado: data/processed/category_translation_clean.csv ((71, 2))